package it.polimi.se2019.adrenalina.controller.event;

public enum EventType {
  AMMO_CARD_UPDATE_EVENT,
  DOUBLE_KILL_EVENT,
  KILLSHOT_EVENT,
  PLAYER_ATTACK_EVENT,
  PLAYER_CHAT_EVENT,
  PLAYER_COLLECT_AMMO_EVENT,
  PLAYER_COLLECT_POWERUP_EVENT,
  PLAYER_COLLECT_WEAPON_EVENT,
  PLAYER_CONNECT_EVENT,
  PLAYER_DEATH_EVENT,
  PLAYER_MOVE_EVENT,
  PLAYER_POWERUP_EVENT,
  PLAYER_RELOAD_EVENT,
  PLAYER_SPAWN_EVENT,
  PLAYER_UPDATE_EVENT,
  SPAWN_POINT_DAMAGE_EVENT,
  WEAPON_UPDATE_EVENT
}
